Add version number checking during release

diff --git a/release b/release
--- a/release
+++ b/release
@@ -1,3 +1,8 @@
+python check_version.py
+if [ $? -ne 0 ]
+    then echo 'Aborting release' && exit 1
+fi
+
 git fetch origin
 git checkout next
 git merge master
