Add Pylint and PEP8 conformance

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,2 +1,14 @@
+echo Running pylint
+pylint vengeance
+if [ $? -ne 0 ]
+    then echo 'Pylint errors' && exit 1
+fi
+
+echo Running pep8
+pep8 vengeance
+if [ $? -ne 0 ]
+    then echo 'PEP8 errors' && exit 1
+fi
+
 python setup.py install
 python vengeance/test/__init___test.py
