Expose Game and Location as part of the API

diff --git a/test b/test
--- a/test
+++ b/test
@@ -25,3 +25,8 @@ python vengeance/test/__init___test.py
 if [ $? -ne 0 ]
     then echo 'Tests failed' && exit 1
 fi
+
+python vengeance/test/game_test.py
+if [ $? -ne 0 ]
+    then echo 'Tests failed' && exit 1
+fi
